// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/streamTeam/football/dribblingEventStreamElementPayload.proto

package ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football;

public final class DribblingEventStreamElementPayloadProtos {
  private DribblingEventStreamElementPayloadProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DribblingEventStreamElementPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:streamTeam.football.DribblingEventStreamElementPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Duration of the dribbling event
     * </pre>
     *
     * <code>int64 duration = 1;</code>
     */
    long getDuration();

    /**
     * <pre>
     * Length of the dribbling event
     * </pre>
     *
     * <code>double length = 2;</code>
     */
    double getLength();

    /**
     * <pre>
     * Velocity of the dribbling event
     * </pre>
     *
     * <code>double velocity = 3;</code>
     */
    double getVelocity();
  }
  /**
   * <pre>
   * Payload of a dribblingEvent stream element
   * </pre>
   *
   * Protobuf type {@code streamTeam.football.DribblingEventStreamElementPayload}
   */
  public  static final class DribblingEventStreamElementPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:streamTeam.football.DribblingEventStreamElementPayload)
      DribblingEventStreamElementPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DribblingEventStreamElementPayload.newBuilder() to construct.
    private DribblingEventStreamElementPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DribblingEventStreamElementPayload() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DribblingEventStreamElementPayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DribblingEventStreamElementPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              duration_ = input.readInt64();
              break;
            }
            case 17: {

              length_ = input.readDouble();
              break;
            }
            case 25: {

              velocity_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.internal_static_streamTeam_football_DribblingEventStreamElementPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.internal_static_streamTeam_football_DribblingEventStreamElementPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.Builder.class);
    }

    public static final int DURATION_FIELD_NUMBER = 1;
    private long duration_;
    /**
     * <pre>
     * Duration of the dribbling event
     * </pre>
     *
     * <code>int64 duration = 1;</code>
     */
    public long getDuration() {
      return duration_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private double length_;
    /**
     * <pre>
     * Length of the dribbling event
     * </pre>
     *
     * <code>double length = 2;</code>
     */
    public double getLength() {
      return length_;
    }

    public static final int VELOCITY_FIELD_NUMBER = 3;
    private double velocity_;
    /**
     * <pre>
     * Velocity of the dribbling event
     * </pre>
     *
     * <code>double velocity = 3;</code>
     */
    public double getVelocity() {
      return velocity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (duration_ != 0L) {
        output.writeInt64(1, duration_);
      }
      if (length_ != 0D) {
        output.writeDouble(2, length_);
      }
      if (velocity_ != 0D) {
        output.writeDouble(3, velocity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (duration_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, duration_);
      }
      if (length_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, length_);
      }
      if (velocity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, velocity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload)) {
        return super.equals(obj);
      }
      ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload other = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload) obj;

      if (getDuration()
          != other.getDuration()) return false;
      if (java.lang.Double.doubleToLongBits(getLength())
          != java.lang.Double.doubleToLongBits(
              other.getLength())) return false;
      if (java.lang.Double.doubleToLongBits(getVelocity())
          != java.lang.Double.doubleToLongBits(
              other.getVelocity())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDuration());
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLength()));
      hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVelocity()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Payload of a dribblingEvent stream element
     * </pre>
     *
     * Protobuf type {@code streamTeam.football.DribblingEventStreamElementPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:streamTeam.football.DribblingEventStreamElementPayload)
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.internal_static_streamTeam_football_DribblingEventStreamElementPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.internal_static_streamTeam_football_DribblingEventStreamElementPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.Builder.class);
      }

      // Construct using ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        duration_ = 0L;

        length_ = 0D;

        velocity_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.internal_static_streamTeam_football_DribblingEventStreamElementPayload_descriptor;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload getDefaultInstanceForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.getDefaultInstance();
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload build() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload buildPartial() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload result = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload(this);
        result.duration_ = duration_;
        result.length_ = length_;
        result.velocity_ = velocity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload) {
          return mergeFrom((ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload other) {
        if (other == ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload.getDefaultInstance()) return this;
        if (other.getDuration() != 0L) {
          setDuration(other.getDuration());
        }
        if (other.getLength() != 0D) {
          setLength(other.getLength());
        }
        if (other.getVelocity() != 0D) {
          setVelocity(other.getVelocity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long duration_ ;
      /**
       * <pre>
       * Duration of the dribbling event
       * </pre>
       *
       * <code>int64 duration = 1;</code>
       */
      public long getDuration() {
        return duration_;
      }
      /**
       * <pre>
       * Duration of the dribbling event
       * </pre>
       *
       * <code>int64 duration = 1;</code>
       */
      public Builder setDuration(long value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Duration of the dribbling event
       * </pre>
       *
       * <code>int64 duration = 1;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0L;
        onChanged();
        return this;
      }

      private double length_ ;
      /**
       * <pre>
       * Length of the dribbling event
       * </pre>
       *
       * <code>double length = 2;</code>
       */
      public double getLength() {
        return length_;
      }
      /**
       * <pre>
       * Length of the dribbling event
       * </pre>
       *
       * <code>double length = 2;</code>
       */
      public Builder setLength(double value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Length of the dribbling event
       * </pre>
       *
       * <code>double length = 2;</code>
       */
      public Builder clearLength() {
        
        length_ = 0D;
        onChanged();
        return this;
      }

      private double velocity_ ;
      /**
       * <pre>
       * Velocity of the dribbling event
       * </pre>
       *
       * <code>double velocity = 3;</code>
       */
      public double getVelocity() {
        return velocity_;
      }
      /**
       * <pre>
       * Velocity of the dribbling event
       * </pre>
       *
       * <code>double velocity = 3;</code>
       */
      public Builder setVelocity(double value) {
        
        velocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Velocity of the dribbling event
       * </pre>
       *
       * <code>double velocity = 3;</code>
       */
      public Builder clearVelocity() {
        
        velocity_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:streamTeam.football.DribblingEventStreamElementPayload)
    }

    // @@protoc_insertion_point(class_scope:streamTeam.football.DribblingEventStreamElementPayload)
    private static final ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload();
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DribblingEventStreamElementPayload>
        PARSER = new com.google.protobuf.AbstractParser<DribblingEventStreamElementPayload>() {
      @java.lang.Override
      public DribblingEventStreamElementPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DribblingEventStreamElementPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DribblingEventStreamElementPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DribblingEventStreamElementPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.DribblingEventStreamElementPayloadProtos.DribblingEventStreamElementPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamTeam_football_DribblingEventStreamElementPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamTeam_football_DribblingEventStreamElementPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nNsrc/main/protobuf/streamTeam/football/" +
      "dribblingEventStreamElementPayload.proto" +
      "\022\023streamTeam.football\"X\n\"DribblingEventS" +
      "treamElementPayload\022\020\n\010duration\030\001 \001(\003\022\016\n" +
      "\006length\030\002 \001(\001\022\020\n\010velocity\030\003 \001(\001Bn\nBch.un" +
      "ibas.dmi.dbis.streamTeam.dataStreamEleme" +
      "nts.protobuf.footballB(DribblingEventStr" +
      "eamElementPayloadProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streamTeam_football_DribblingEventStreamElementPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamTeam_football_DribblingEventStreamElementPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamTeam_football_DribblingEventStreamElementPayload_descriptor,
        new java.lang.String[] { "Duration", "Length", "Velocity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
