// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/streamTeam/football/fieldObjectStateStreamElementPayload.proto

package ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football;

public final class FieldObjectStateStreamElementPayloadProtos {
  private FieldObjectStateStreamElementPayloadProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FieldObjectStateStreamElementPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:streamTeam.football.FieldObjectStateStreamElementPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * X component of the velocity
     * </pre>
     *
     * <code>double vx = 1;</code>
     */
    double getVx();

    /**
     * <pre>
     * Y component of the velocity
     * </pre>
     *
     * <code>double vy = 2;</code>
     */
    double getVy();

    /**
     * <pre>
     * Z component of the velocity
     * </pre>
     *
     * <code>double vz = 3;</code>
     */
    double getVz();

    /**
     * <pre>
     * Absolute velocity
     * </pre>
     *
     * <code>double vabs = 4;</code>
     */
    double getVabs();
  }
  /**
   * <pre>
   * Payload of a fieldObjectState stream element
   * </pre>
   *
   * Protobuf type {@code streamTeam.football.FieldObjectStateStreamElementPayload}
   */
  public  static final class FieldObjectStateStreamElementPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:streamTeam.football.FieldObjectStateStreamElementPayload)
      FieldObjectStateStreamElementPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FieldObjectStateStreamElementPayload.newBuilder() to construct.
    private FieldObjectStateStreamElementPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FieldObjectStateStreamElementPayload() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FieldObjectStateStreamElementPayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FieldObjectStateStreamElementPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              vx_ = input.readDouble();
              break;
            }
            case 17: {

              vy_ = input.readDouble();
              break;
            }
            case 25: {

              vz_ = input.readDouble();
              break;
            }
            case 33: {

              vabs_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.Builder.class);
    }

    public static final int VX_FIELD_NUMBER = 1;
    private double vx_;
    /**
     * <pre>
     * X component of the velocity
     * </pre>
     *
     * <code>double vx = 1;</code>
     */
    public double getVx() {
      return vx_;
    }

    public static final int VY_FIELD_NUMBER = 2;
    private double vy_;
    /**
     * <pre>
     * Y component of the velocity
     * </pre>
     *
     * <code>double vy = 2;</code>
     */
    public double getVy() {
      return vy_;
    }

    public static final int VZ_FIELD_NUMBER = 3;
    private double vz_;
    /**
     * <pre>
     * Z component of the velocity
     * </pre>
     *
     * <code>double vz = 3;</code>
     */
    public double getVz() {
      return vz_;
    }

    public static final int VABS_FIELD_NUMBER = 4;
    private double vabs_;
    /**
     * <pre>
     * Absolute velocity
     * </pre>
     *
     * <code>double vabs = 4;</code>
     */
    public double getVabs() {
      return vabs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vx_ != 0D) {
        output.writeDouble(1, vx_);
      }
      if (vy_ != 0D) {
        output.writeDouble(2, vy_);
      }
      if (vz_ != 0D) {
        output.writeDouble(3, vz_);
      }
      if (vabs_ != 0D) {
        output.writeDouble(4, vabs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vx_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, vx_);
      }
      if (vy_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, vy_);
      }
      if (vz_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, vz_);
      }
      if (vabs_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, vabs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload)) {
        return super.equals(obj);
      }
      ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload other = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload) obj;

      if (java.lang.Double.doubleToLongBits(getVx())
          != java.lang.Double.doubleToLongBits(
              other.getVx())) return false;
      if (java.lang.Double.doubleToLongBits(getVy())
          != java.lang.Double.doubleToLongBits(
              other.getVy())) return false;
      if (java.lang.Double.doubleToLongBits(getVz())
          != java.lang.Double.doubleToLongBits(
              other.getVz())) return false;
      if (java.lang.Double.doubleToLongBits(getVabs())
          != java.lang.Double.doubleToLongBits(
              other.getVabs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVx()));
      hash = (37 * hash) + VY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVy()));
      hash = (37 * hash) + VZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVz()));
      hash = (37 * hash) + VABS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVabs()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Payload of a fieldObjectState stream element
     * </pre>
     *
     * Protobuf type {@code streamTeam.football.FieldObjectStateStreamElementPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:streamTeam.football.FieldObjectStateStreamElementPayload)
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.Builder.class);
      }

      // Construct using ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vx_ = 0D;

        vy_ = 0D;

        vz_ = 0D;

        vabs_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_descriptor;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload getDefaultInstanceForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.getDefaultInstance();
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload build() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload buildPartial() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload result = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload(this);
        result.vx_ = vx_;
        result.vy_ = vy_;
        result.vz_ = vz_;
        result.vabs_ = vabs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload) {
          return mergeFrom((ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload other) {
        if (other == ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload.getDefaultInstance()) return this;
        if (other.getVx() != 0D) {
          setVx(other.getVx());
        }
        if (other.getVy() != 0D) {
          setVy(other.getVy());
        }
        if (other.getVz() != 0D) {
          setVz(other.getVz());
        }
        if (other.getVabs() != 0D) {
          setVabs(other.getVabs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double vx_ ;
      /**
       * <pre>
       * X component of the velocity
       * </pre>
       *
       * <code>double vx = 1;</code>
       */
      public double getVx() {
        return vx_;
      }
      /**
       * <pre>
       * X component of the velocity
       * </pre>
       *
       * <code>double vx = 1;</code>
       */
      public Builder setVx(double value) {
        
        vx_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * X component of the velocity
       * </pre>
       *
       * <code>double vx = 1;</code>
       */
      public Builder clearVx() {
        
        vx_ = 0D;
        onChanged();
        return this;
      }

      private double vy_ ;
      /**
       * <pre>
       * Y component of the velocity
       * </pre>
       *
       * <code>double vy = 2;</code>
       */
      public double getVy() {
        return vy_;
      }
      /**
       * <pre>
       * Y component of the velocity
       * </pre>
       *
       * <code>double vy = 2;</code>
       */
      public Builder setVy(double value) {
        
        vy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Y component of the velocity
       * </pre>
       *
       * <code>double vy = 2;</code>
       */
      public Builder clearVy() {
        
        vy_ = 0D;
        onChanged();
        return this;
      }

      private double vz_ ;
      /**
       * <pre>
       * Z component of the velocity
       * </pre>
       *
       * <code>double vz = 3;</code>
       */
      public double getVz() {
        return vz_;
      }
      /**
       * <pre>
       * Z component of the velocity
       * </pre>
       *
       * <code>double vz = 3;</code>
       */
      public Builder setVz(double value) {
        
        vz_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Z component of the velocity
       * </pre>
       *
       * <code>double vz = 3;</code>
       */
      public Builder clearVz() {
        
        vz_ = 0D;
        onChanged();
        return this;
      }

      private double vabs_ ;
      /**
       * <pre>
       * Absolute velocity
       * </pre>
       *
       * <code>double vabs = 4;</code>
       */
      public double getVabs() {
        return vabs_;
      }
      /**
       * <pre>
       * Absolute velocity
       * </pre>
       *
       * <code>double vabs = 4;</code>
       */
      public Builder setVabs(double value) {
        
        vabs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Absolute velocity
       * </pre>
       *
       * <code>double vabs = 4;</code>
       */
      public Builder clearVabs() {
        
        vabs_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:streamTeam.football.FieldObjectStateStreamElementPayload)
    }

    // @@protoc_insertion_point(class_scope:streamTeam.football.FieldObjectStateStreamElementPayload)
    private static final ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload();
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FieldObjectStateStreamElementPayload>
        PARSER = new com.google.protobuf.AbstractParser<FieldObjectStateStreamElementPayload>() {
      @java.lang.Override
      public FieldObjectStateStreamElementPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FieldObjectStateStreamElementPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FieldObjectStateStreamElementPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FieldObjectStateStreamElementPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.FieldObjectStateStreamElementPayloadProtos.FieldObjectStateStreamElementPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nPsrc/main/protobuf/streamTeam/football/" +
      "fieldObjectStateStreamElementPayload.pro" +
      "to\022\023streamTeam.football\"X\n$FieldObjectSt" +
      "ateStreamElementPayload\022\n\n\002vx\030\001 \001(\001\022\n\n\002v" +
      "y\030\002 \001(\001\022\n\n\002vz\030\003 \001(\001\022\014\n\004vabs\030\004 \001(\001Bp\nBch." +
      "unibas.dmi.dbis.streamTeam.dataStreamEle" +
      "ments.protobuf.footballB*FieldObjectStat" +
      "eStreamElementPayloadProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamTeam_football_FieldObjectStateStreamElementPayload_descriptor,
        new java.lang.String[] { "Vx", "Vy", "Vz", "Vabs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
