// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/streamTeam/football/matchMetadataStreamElementPayload.proto

package ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football;

public final class MatchMetadataStreamElementPayloadProtos {
  private MatchMetadataStreamElementPayloadProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MatchMetadataStreamElementPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:streamTeam.football.MatchMetadataStreamElementPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The generation timestamp of the first data stream element of the match
     * </pre>
     *
     * <code>int64 generationTimestampFirstDataStreamElementOfTheMatch = 1;</code>
     */
    long getGenerationTimestampFirstDataStreamElementOfTheMatch();

    /**
     * <pre>
     * Sports discipline (e.g., "Football" or "Ice hockey")
     * </pre>
     *
     * <code>string sport = 2;</code>
     */
    java.lang.String getSport();
    /**
     * <pre>
     * Sports discipline (e.g., "Football" or "Ice hockey")
     * </pre>
     *
     * <code>string sport = 2;</code>
     */
    com.google.protobuf.ByteString
        getSportBytes();

    /**
     * <pre>
     * Length of the field in m (e.g., 105.0)
     * </pre>
     *
     * <code>double fieldLength = 3;</code>
     */
    double getFieldLength();

    /**
     * <pre>
     * Width of the field in m (e.g., 68.0)
     * </pre>
     *
     * <code>double fieldWidth = 4;</code>
     */
    double getFieldWidth();

    /**
     * <pre>
     * Boolean which specifies if the x coordinate of the tracked positions is mirrored
     * </pre>
     *
     * <code>bool mirroredX = 5;</code>
     */
    boolean getMirroredX();

    /**
     * <pre>
     * Boolean which specifies if the y coordinate of the tracked positions is mirrored
     * </pre>
     *
     * <code>bool mirroredY = 6;</code>
     */
    boolean getMirroredY();

    /**
     * <pre>
     * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
     * </pre>
     *
     * <code>string areaInfos = 7;</code>
     */
    java.lang.String getAreaInfos();
    /**
     * <pre>
     * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
     * </pre>
     *
     * <code>string areaInfos = 7;</code>
     */
    com.google.protobuf.ByteString
        getAreaInfosBytes();

    /**
     * <pre>
     * Unix timestamp specifying the start of the match
     * </pre>
     *
     * <code>int64 matchStartUnixTs = 8;</code>
     */
    long getMatchStartUnixTs();

    /**
     * <pre>
     * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
     * </pre>
     *
     * <code>string competition = 9;</code>
     */
    java.lang.String getCompetition();
    /**
     * <pre>
     * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
     * </pre>
     *
     * <code>string competition = 9;</code>
     */
    com.google.protobuf.ByteString
        getCompetitionBytes();

    /**
     * <pre>
     * Venue (e.g., "St. Jakob-Park" or "Maracana")
     * </pre>
     *
     * <code>string venue = 10;</code>
     */
    java.lang.String getVenue();
    /**
     * <pre>
     * Venue (e.g., "St. Jakob-Park" or "Maracana")
     * </pre>
     *
     * <code>string venue = 10;</code>
     */
    com.google.protobuf.ByteString
        getVenueBytes();

    /**
     * <pre>
     * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
     * </pre>
     *
     * <code>string objectRenameMap = 11;</code>
     */
    java.lang.String getObjectRenameMap();
    /**
     * <pre>
     * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
     * </pre>
     *
     * <code>string objectRenameMap = 11;</code>
     */
    com.google.protobuf.ByteString
        getObjectRenameMapBytes();

    /**
     * <pre>
     * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
     * </pre>
     *
     * <code>string teamRenameMap = 12;</code>
     */
    java.lang.String getTeamRenameMap();
    /**
     * <pre>
     * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
     * </pre>
     *
     * <code>string teamRenameMap = 12;</code>
     */
    com.google.protobuf.ByteString
        getTeamRenameMapBytes();

    /**
     * <pre>
     * Path to the video file
     * </pre>
     *
     * <code>string videoPath = 13;</code>
     */
    java.lang.String getVideoPath();
    /**
     * <pre>
     * Path to the video file
     * </pre>
     *
     * <code>string videoPath = 13;</code>
     */
    com.google.protobuf.ByteString
        getVideoPathBytes();

    /**
     * <pre>
     * Video offset (in s) of the start of the match
     * </pre>
     *
     * <code>int64 matchStartVideoOffset = 14;</code>
     */
    long getMatchStartVideoOffset();

    /**
     * <pre>
     * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
     * </pre>
     *
     * <code>string teamColorMap = 15;</code>
     */
    java.lang.String getTeamColorMap();
    /**
     * <pre>
     * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
     * </pre>
     *
     * <code>string teamColorMap = 15;</code>
     */
    com.google.protobuf.ByteString
        getTeamColorMapBytes();
  }
  /**
   * <pre>
   * Payload of a matchMetadata stream element
   * </pre>
   *
   * Protobuf type {@code streamTeam.football.MatchMetadataStreamElementPayload}
   */
  public  static final class MatchMetadataStreamElementPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:streamTeam.football.MatchMetadataStreamElementPayload)
      MatchMetadataStreamElementPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MatchMetadataStreamElementPayload.newBuilder() to construct.
    private MatchMetadataStreamElementPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MatchMetadataStreamElementPayload() {
      sport_ = "";
      areaInfos_ = "";
      competition_ = "";
      venue_ = "";
      objectRenameMap_ = "";
      teamRenameMap_ = "";
      videoPath_ = "";
      teamColorMap_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MatchMetadataStreamElementPayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MatchMetadataStreamElementPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              generationTimestampFirstDataStreamElementOfTheMatch_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sport_ = s;
              break;
            }
            case 25: {

              fieldLength_ = input.readDouble();
              break;
            }
            case 33: {

              fieldWidth_ = input.readDouble();
              break;
            }
            case 40: {

              mirroredX_ = input.readBool();
              break;
            }
            case 48: {

              mirroredY_ = input.readBool();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              areaInfos_ = s;
              break;
            }
            case 64: {

              matchStartUnixTs_ = input.readInt64();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              competition_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              venue_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              objectRenameMap_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              teamRenameMap_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              videoPath_ = s;
              break;
            }
            case 112: {

              matchStartVideoOffset_ = input.readInt64();
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              teamColorMap_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.internal_static_streamTeam_football_MatchMetadataStreamElementPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.internal_static_streamTeam_football_MatchMetadataStreamElementPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.Builder.class);
    }

    public static final int GENERATIONTIMESTAMPFIRSTDATASTREAMELEMENTOFTHEMATCH_FIELD_NUMBER = 1;
    private long generationTimestampFirstDataStreamElementOfTheMatch_;
    /**
     * <pre>
     * The generation timestamp of the first data stream element of the match
     * </pre>
     *
     * <code>int64 generationTimestampFirstDataStreamElementOfTheMatch = 1;</code>
     */
    public long getGenerationTimestampFirstDataStreamElementOfTheMatch() {
      return generationTimestampFirstDataStreamElementOfTheMatch_;
    }

    public static final int SPORT_FIELD_NUMBER = 2;
    private volatile java.lang.Object sport_;
    /**
     * <pre>
     * Sports discipline (e.g., "Football" or "Ice hockey")
     * </pre>
     *
     * <code>string sport = 2;</code>
     */
    public java.lang.String getSport() {
      java.lang.Object ref = sport_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sport_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sports discipline (e.g., "Football" or "Ice hockey")
     * </pre>
     *
     * <code>string sport = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSportBytes() {
      java.lang.Object ref = sport_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDLENGTH_FIELD_NUMBER = 3;
    private double fieldLength_;
    /**
     * <pre>
     * Length of the field in m (e.g., 105.0)
     * </pre>
     *
     * <code>double fieldLength = 3;</code>
     */
    public double getFieldLength() {
      return fieldLength_;
    }

    public static final int FIELDWIDTH_FIELD_NUMBER = 4;
    private double fieldWidth_;
    /**
     * <pre>
     * Width of the field in m (e.g., 68.0)
     * </pre>
     *
     * <code>double fieldWidth = 4;</code>
     */
    public double getFieldWidth() {
      return fieldWidth_;
    }

    public static final int MIRROREDX_FIELD_NUMBER = 5;
    private boolean mirroredX_;
    /**
     * <pre>
     * Boolean which specifies if the x coordinate of the tracked positions is mirrored
     * </pre>
     *
     * <code>bool mirroredX = 5;</code>
     */
    public boolean getMirroredX() {
      return mirroredX_;
    }

    public static final int MIRROREDY_FIELD_NUMBER = 6;
    private boolean mirroredY_;
    /**
     * <pre>
     * Boolean which specifies if the y coordinate of the tracked positions is mirrored
     * </pre>
     *
     * <code>bool mirroredY = 6;</code>
     */
    public boolean getMirroredY() {
      return mirroredY_;
    }

    public static final int AREAINFOS_FIELD_NUMBER = 7;
    private volatile java.lang.Object areaInfos_;
    /**
     * <pre>
     * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
     * </pre>
     *
     * <code>string areaInfos = 7;</code>
     */
    public java.lang.String getAreaInfos() {
      java.lang.Object ref = areaInfos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        areaInfos_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
     * </pre>
     *
     * <code>string areaInfos = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAreaInfosBytes() {
      java.lang.Object ref = areaInfos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        areaInfos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHSTARTUNIXTS_FIELD_NUMBER = 8;
    private long matchStartUnixTs_;
    /**
     * <pre>
     * Unix timestamp specifying the start of the match
     * </pre>
     *
     * <code>int64 matchStartUnixTs = 8;</code>
     */
    public long getMatchStartUnixTs() {
      return matchStartUnixTs_;
    }

    public static final int COMPETITION_FIELD_NUMBER = 9;
    private volatile java.lang.Object competition_;
    /**
     * <pre>
     * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
     * </pre>
     *
     * <code>string competition = 9;</code>
     */
    public java.lang.String getCompetition() {
      java.lang.Object ref = competition_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        competition_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
     * </pre>
     *
     * <code>string competition = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCompetitionBytes() {
      java.lang.Object ref = competition_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        competition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VENUE_FIELD_NUMBER = 10;
    private volatile java.lang.Object venue_;
    /**
     * <pre>
     * Venue (e.g., "St. Jakob-Park" or "Maracana")
     * </pre>
     *
     * <code>string venue = 10;</code>
     */
    public java.lang.String getVenue() {
      java.lang.Object ref = venue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        venue_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Venue (e.g., "St. Jakob-Park" or "Maracana")
     * </pre>
     *
     * <code>string venue = 10;</code>
     */
    public com.google.protobuf.ByteString
        getVenueBytes() {
      java.lang.Object ref = venue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        venue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OBJECTRENAMEMAP_FIELD_NUMBER = 11;
    private volatile java.lang.Object objectRenameMap_;
    /**
     * <pre>
     * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
     * </pre>
     *
     * <code>string objectRenameMap = 11;</code>
     */
    public java.lang.String getObjectRenameMap() {
      java.lang.Object ref = objectRenameMap_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectRenameMap_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
     * </pre>
     *
     * <code>string objectRenameMap = 11;</code>
     */
    public com.google.protobuf.ByteString
        getObjectRenameMapBytes() {
      java.lang.Object ref = objectRenameMap_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectRenameMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEAMRENAMEMAP_FIELD_NUMBER = 12;
    private volatile java.lang.Object teamRenameMap_;
    /**
     * <pre>
     * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
     * </pre>
     *
     * <code>string teamRenameMap = 12;</code>
     */
    public java.lang.String getTeamRenameMap() {
      java.lang.Object ref = teamRenameMap_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teamRenameMap_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
     * </pre>
     *
     * <code>string teamRenameMap = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTeamRenameMapBytes() {
      java.lang.Object ref = teamRenameMap_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamRenameMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIDEOPATH_FIELD_NUMBER = 13;
    private volatile java.lang.Object videoPath_;
    /**
     * <pre>
     * Path to the video file
     * </pre>
     *
     * <code>string videoPath = 13;</code>
     */
    public java.lang.String getVideoPath() {
      java.lang.Object ref = videoPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        videoPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Path to the video file
     * </pre>
     *
     * <code>string videoPath = 13;</code>
     */
    public com.google.protobuf.ByteString
        getVideoPathBytes() {
      java.lang.Object ref = videoPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHSTARTVIDEOOFFSET_FIELD_NUMBER = 14;
    private long matchStartVideoOffset_;
    /**
     * <pre>
     * Video offset (in s) of the start of the match
     * </pre>
     *
     * <code>int64 matchStartVideoOffset = 14;</code>
     */
    public long getMatchStartVideoOffset() {
      return matchStartVideoOffset_;
    }

    public static final int TEAMCOLORMAP_FIELD_NUMBER = 15;
    private volatile java.lang.Object teamColorMap_;
    /**
     * <pre>
     * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
     * </pre>
     *
     * <code>string teamColorMap = 15;</code>
     */
    public java.lang.String getTeamColorMap() {
      java.lang.Object ref = teamColorMap_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teamColorMap_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
     * </pre>
     *
     * <code>string teamColorMap = 15;</code>
     */
    public com.google.protobuf.ByteString
        getTeamColorMapBytes() {
      java.lang.Object ref = teamColorMap_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teamColorMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (generationTimestampFirstDataStreamElementOfTheMatch_ != 0L) {
        output.writeInt64(1, generationTimestampFirstDataStreamElementOfTheMatch_);
      }
      if (!getSportBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sport_);
      }
      if (fieldLength_ != 0D) {
        output.writeDouble(3, fieldLength_);
      }
      if (fieldWidth_ != 0D) {
        output.writeDouble(4, fieldWidth_);
      }
      if (mirroredX_ != false) {
        output.writeBool(5, mirroredX_);
      }
      if (mirroredY_ != false) {
        output.writeBool(6, mirroredY_);
      }
      if (!getAreaInfosBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, areaInfos_);
      }
      if (matchStartUnixTs_ != 0L) {
        output.writeInt64(8, matchStartUnixTs_);
      }
      if (!getCompetitionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, competition_);
      }
      if (!getVenueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, venue_);
      }
      if (!getObjectRenameMapBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, objectRenameMap_);
      }
      if (!getTeamRenameMapBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, teamRenameMap_);
      }
      if (!getVideoPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, videoPath_);
      }
      if (matchStartVideoOffset_ != 0L) {
        output.writeInt64(14, matchStartVideoOffset_);
      }
      if (!getTeamColorMapBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, teamColorMap_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (generationTimestampFirstDataStreamElementOfTheMatch_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, generationTimestampFirstDataStreamElementOfTheMatch_);
      }
      if (!getSportBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sport_);
      }
      if (fieldLength_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, fieldLength_);
      }
      if (fieldWidth_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, fieldWidth_);
      }
      if (mirroredX_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, mirroredX_);
      }
      if (mirroredY_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, mirroredY_);
      }
      if (!getAreaInfosBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, areaInfos_);
      }
      if (matchStartUnixTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, matchStartUnixTs_);
      }
      if (!getCompetitionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, competition_);
      }
      if (!getVenueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, venue_);
      }
      if (!getObjectRenameMapBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, objectRenameMap_);
      }
      if (!getTeamRenameMapBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, teamRenameMap_);
      }
      if (!getVideoPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, videoPath_);
      }
      if (matchStartVideoOffset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, matchStartVideoOffset_);
      }
      if (!getTeamColorMapBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, teamColorMap_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload)) {
        return super.equals(obj);
      }
      ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload other = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload) obj;

      if (getGenerationTimestampFirstDataStreamElementOfTheMatch()
          != other.getGenerationTimestampFirstDataStreamElementOfTheMatch()) return false;
      if (!getSport()
          .equals(other.getSport())) return false;
      if (java.lang.Double.doubleToLongBits(getFieldLength())
          != java.lang.Double.doubleToLongBits(
              other.getFieldLength())) return false;
      if (java.lang.Double.doubleToLongBits(getFieldWidth())
          != java.lang.Double.doubleToLongBits(
              other.getFieldWidth())) return false;
      if (getMirroredX()
          != other.getMirroredX()) return false;
      if (getMirroredY()
          != other.getMirroredY()) return false;
      if (!getAreaInfos()
          .equals(other.getAreaInfos())) return false;
      if (getMatchStartUnixTs()
          != other.getMatchStartUnixTs()) return false;
      if (!getCompetition()
          .equals(other.getCompetition())) return false;
      if (!getVenue()
          .equals(other.getVenue())) return false;
      if (!getObjectRenameMap()
          .equals(other.getObjectRenameMap())) return false;
      if (!getTeamRenameMap()
          .equals(other.getTeamRenameMap())) return false;
      if (!getVideoPath()
          .equals(other.getVideoPath())) return false;
      if (getMatchStartVideoOffset()
          != other.getMatchStartVideoOffset()) return false;
      if (!getTeamColorMap()
          .equals(other.getTeamColorMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GENERATIONTIMESTAMPFIRSTDATASTREAMELEMENTOFTHEMATCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGenerationTimestampFirstDataStreamElementOfTheMatch());
      hash = (37 * hash) + SPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSport().hashCode();
      hash = (37 * hash) + FIELDLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFieldLength()));
      hash = (37 * hash) + FIELDWIDTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFieldWidth()));
      hash = (37 * hash) + MIRROREDX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMirroredX());
      hash = (37 * hash) + MIRROREDY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMirroredY());
      hash = (37 * hash) + AREAINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getAreaInfos().hashCode();
      hash = (37 * hash) + MATCHSTARTUNIXTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMatchStartUnixTs());
      hash = (37 * hash) + COMPETITION_FIELD_NUMBER;
      hash = (53 * hash) + getCompetition().hashCode();
      hash = (37 * hash) + VENUE_FIELD_NUMBER;
      hash = (53 * hash) + getVenue().hashCode();
      hash = (37 * hash) + OBJECTRENAMEMAP_FIELD_NUMBER;
      hash = (53 * hash) + getObjectRenameMap().hashCode();
      hash = (37 * hash) + TEAMRENAMEMAP_FIELD_NUMBER;
      hash = (53 * hash) + getTeamRenameMap().hashCode();
      hash = (37 * hash) + VIDEOPATH_FIELD_NUMBER;
      hash = (53 * hash) + getVideoPath().hashCode();
      hash = (37 * hash) + MATCHSTARTVIDEOOFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMatchStartVideoOffset());
      hash = (37 * hash) + TEAMCOLORMAP_FIELD_NUMBER;
      hash = (53 * hash) + getTeamColorMap().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Payload of a matchMetadata stream element
     * </pre>
     *
     * Protobuf type {@code streamTeam.football.MatchMetadataStreamElementPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:streamTeam.football.MatchMetadataStreamElementPayload)
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.internal_static_streamTeam_football_MatchMetadataStreamElementPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.internal_static_streamTeam_football_MatchMetadataStreamElementPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.Builder.class);
      }

      // Construct using ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        generationTimestampFirstDataStreamElementOfTheMatch_ = 0L;

        sport_ = "";

        fieldLength_ = 0D;

        fieldWidth_ = 0D;

        mirroredX_ = false;

        mirroredY_ = false;

        areaInfos_ = "";

        matchStartUnixTs_ = 0L;

        competition_ = "";

        venue_ = "";

        objectRenameMap_ = "";

        teamRenameMap_ = "";

        videoPath_ = "";

        matchStartVideoOffset_ = 0L;

        teamColorMap_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.internal_static_streamTeam_football_MatchMetadataStreamElementPayload_descriptor;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload getDefaultInstanceForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.getDefaultInstance();
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload build() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload buildPartial() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload result = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload(this);
        result.generationTimestampFirstDataStreamElementOfTheMatch_ = generationTimestampFirstDataStreamElementOfTheMatch_;
        result.sport_ = sport_;
        result.fieldLength_ = fieldLength_;
        result.fieldWidth_ = fieldWidth_;
        result.mirroredX_ = mirroredX_;
        result.mirroredY_ = mirroredY_;
        result.areaInfos_ = areaInfos_;
        result.matchStartUnixTs_ = matchStartUnixTs_;
        result.competition_ = competition_;
        result.venue_ = venue_;
        result.objectRenameMap_ = objectRenameMap_;
        result.teamRenameMap_ = teamRenameMap_;
        result.videoPath_ = videoPath_;
        result.matchStartVideoOffset_ = matchStartVideoOffset_;
        result.teamColorMap_ = teamColorMap_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload) {
          return mergeFrom((ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload other) {
        if (other == ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload.getDefaultInstance()) return this;
        if (other.getGenerationTimestampFirstDataStreamElementOfTheMatch() != 0L) {
          setGenerationTimestampFirstDataStreamElementOfTheMatch(other.getGenerationTimestampFirstDataStreamElementOfTheMatch());
        }
        if (!other.getSport().isEmpty()) {
          sport_ = other.sport_;
          onChanged();
        }
        if (other.getFieldLength() != 0D) {
          setFieldLength(other.getFieldLength());
        }
        if (other.getFieldWidth() != 0D) {
          setFieldWidth(other.getFieldWidth());
        }
        if (other.getMirroredX() != false) {
          setMirroredX(other.getMirroredX());
        }
        if (other.getMirroredY() != false) {
          setMirroredY(other.getMirroredY());
        }
        if (!other.getAreaInfos().isEmpty()) {
          areaInfos_ = other.areaInfos_;
          onChanged();
        }
        if (other.getMatchStartUnixTs() != 0L) {
          setMatchStartUnixTs(other.getMatchStartUnixTs());
        }
        if (!other.getCompetition().isEmpty()) {
          competition_ = other.competition_;
          onChanged();
        }
        if (!other.getVenue().isEmpty()) {
          venue_ = other.venue_;
          onChanged();
        }
        if (!other.getObjectRenameMap().isEmpty()) {
          objectRenameMap_ = other.objectRenameMap_;
          onChanged();
        }
        if (!other.getTeamRenameMap().isEmpty()) {
          teamRenameMap_ = other.teamRenameMap_;
          onChanged();
        }
        if (!other.getVideoPath().isEmpty()) {
          videoPath_ = other.videoPath_;
          onChanged();
        }
        if (other.getMatchStartVideoOffset() != 0L) {
          setMatchStartVideoOffset(other.getMatchStartVideoOffset());
        }
        if (!other.getTeamColorMap().isEmpty()) {
          teamColorMap_ = other.teamColorMap_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long generationTimestampFirstDataStreamElementOfTheMatch_ ;
      /**
       * <pre>
       * The generation timestamp of the first data stream element of the match
       * </pre>
       *
       * <code>int64 generationTimestampFirstDataStreamElementOfTheMatch = 1;</code>
       */
      public long getGenerationTimestampFirstDataStreamElementOfTheMatch() {
        return generationTimestampFirstDataStreamElementOfTheMatch_;
      }
      /**
       * <pre>
       * The generation timestamp of the first data stream element of the match
       * </pre>
       *
       * <code>int64 generationTimestampFirstDataStreamElementOfTheMatch = 1;</code>
       */
      public Builder setGenerationTimestampFirstDataStreamElementOfTheMatch(long value) {
        
        generationTimestampFirstDataStreamElementOfTheMatch_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The generation timestamp of the first data stream element of the match
       * </pre>
       *
       * <code>int64 generationTimestampFirstDataStreamElementOfTheMatch = 1;</code>
       */
      public Builder clearGenerationTimestampFirstDataStreamElementOfTheMatch() {
        
        generationTimestampFirstDataStreamElementOfTheMatch_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sport_ = "";
      /**
       * <pre>
       * Sports discipline (e.g., "Football" or "Ice hockey")
       * </pre>
       *
       * <code>string sport = 2;</code>
       */
      public java.lang.String getSport() {
        java.lang.Object ref = sport_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sport_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sports discipline (e.g., "Football" or "Ice hockey")
       * </pre>
       *
       * <code>string sport = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSportBytes() {
        java.lang.Object ref = sport_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sport_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sports discipline (e.g., "Football" or "Ice hockey")
       * </pre>
       *
       * <code>string sport = 2;</code>
       */
      public Builder setSport(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sport_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sports discipline (e.g., "Football" or "Ice hockey")
       * </pre>
       *
       * <code>string sport = 2;</code>
       */
      public Builder clearSport() {
        
        sport_ = getDefaultInstance().getSport();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sports discipline (e.g., "Football" or "Ice hockey")
       * </pre>
       *
       * <code>string sport = 2;</code>
       */
      public Builder setSportBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sport_ = value;
        onChanged();
        return this;
      }

      private double fieldLength_ ;
      /**
       * <pre>
       * Length of the field in m (e.g., 105.0)
       * </pre>
       *
       * <code>double fieldLength = 3;</code>
       */
      public double getFieldLength() {
        return fieldLength_;
      }
      /**
       * <pre>
       * Length of the field in m (e.g., 105.0)
       * </pre>
       *
       * <code>double fieldLength = 3;</code>
       */
      public Builder setFieldLength(double value) {
        
        fieldLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Length of the field in m (e.g., 105.0)
       * </pre>
       *
       * <code>double fieldLength = 3;</code>
       */
      public Builder clearFieldLength() {
        
        fieldLength_ = 0D;
        onChanged();
        return this;
      }

      private double fieldWidth_ ;
      /**
       * <pre>
       * Width of the field in m (e.g., 68.0)
       * </pre>
       *
       * <code>double fieldWidth = 4;</code>
       */
      public double getFieldWidth() {
        return fieldWidth_;
      }
      /**
       * <pre>
       * Width of the field in m (e.g., 68.0)
       * </pre>
       *
       * <code>double fieldWidth = 4;</code>
       */
      public Builder setFieldWidth(double value) {
        
        fieldWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Width of the field in m (e.g., 68.0)
       * </pre>
       *
       * <code>double fieldWidth = 4;</code>
       */
      public Builder clearFieldWidth() {
        
        fieldWidth_ = 0D;
        onChanged();
        return this;
      }

      private boolean mirroredX_ ;
      /**
       * <pre>
       * Boolean which specifies if the x coordinate of the tracked positions is mirrored
       * </pre>
       *
       * <code>bool mirroredX = 5;</code>
       */
      public boolean getMirroredX() {
        return mirroredX_;
      }
      /**
       * <pre>
       * Boolean which specifies if the x coordinate of the tracked positions is mirrored
       * </pre>
       *
       * <code>bool mirroredX = 5;</code>
       */
      public Builder setMirroredX(boolean value) {
        
        mirroredX_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Boolean which specifies if the x coordinate of the tracked positions is mirrored
       * </pre>
       *
       * <code>bool mirroredX = 5;</code>
       */
      public Builder clearMirroredX() {
        
        mirroredX_ = false;
        onChanged();
        return this;
      }

      private boolean mirroredY_ ;
      /**
       * <pre>
       * Boolean which specifies if the y coordinate of the tracked positions is mirrored
       * </pre>
       *
       * <code>bool mirroredY = 6;</code>
       */
      public boolean getMirroredY() {
        return mirroredY_;
      }
      /**
       * <pre>
       * Boolean which specifies if the y coordinate of the tracked positions is mirrored
       * </pre>
       *
       * <code>bool mirroredY = 6;</code>
       */
      public Builder setMirroredY(boolean value) {
        
        mirroredY_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Boolean which specifies if the y coordinate of the tracked positions is mirrored
       * </pre>
       *
       * <code>bool mirroredY = 6;</code>
       */
      public Builder clearMirroredY() {
        
        mirroredY_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object areaInfos_ = "";
      /**
       * <pre>
       * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
       * </pre>
       *
       * <code>string areaInfos = 7;</code>
       */
      public java.lang.String getAreaInfos() {
        java.lang.Object ref = areaInfos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          areaInfos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
       * </pre>
       *
       * <code>string areaInfos = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAreaInfosBytes() {
        java.lang.Object ref = areaInfos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          areaInfos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
       * </pre>
       *
       * <code>string areaInfos = 7;</code>
       */
      public Builder setAreaInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        areaInfos_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
       * </pre>
       *
       * <code>string areaInfos = 7;</code>
       */
      public Builder clearAreaInfos() {
        
        areaInfos_ = getDefaultInstance().getAreaInfos();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of area infos (e.g., {field:-52.5&#64;52.5&#64;-34.0&#64;34.0},{leftThird:-52.5&#64;-17.5&#64;-34.0&#64;34.0},{centerThird:-17.5&#64;17.5&#64;-34.0&#64;34.0},...")
       * </pre>
       *
       * <code>string areaInfos = 7;</code>
       */
      public Builder setAreaInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        areaInfos_ = value;
        onChanged();
        return this;
      }

      private long matchStartUnixTs_ ;
      /**
       * <pre>
       * Unix timestamp specifying the start of the match
       * </pre>
       *
       * <code>int64 matchStartUnixTs = 8;</code>
       */
      public long getMatchStartUnixTs() {
        return matchStartUnixTs_;
      }
      /**
       * <pre>
       * Unix timestamp specifying the start of the match
       * </pre>
       *
       * <code>int64 matchStartUnixTs = 8;</code>
       */
      public Builder setMatchStartUnixTs(long value) {
        
        matchStartUnixTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unix timestamp specifying the start of the match
       * </pre>
       *
       * <code>int64 matchStartUnixTs = 8;</code>
       */
      public Builder clearMatchStartUnixTs() {
        
        matchStartUnixTs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object competition_ = "";
      /**
       * <pre>
       * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
       * </pre>
       *
       * <code>string competition = 9;</code>
       */
      public java.lang.String getCompetition() {
        java.lang.Object ref = competition_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          competition_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
       * </pre>
       *
       * <code>string competition = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCompetitionBytes() {
        java.lang.Object ref = competition_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          competition_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
       * </pre>
       *
       * <code>string competition = 9;</code>
       */
      public Builder setCompetition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        competition_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
       * </pre>
       *
       * <code>string competition = 9;</code>
       */
      public Builder clearCompetition() {
        
        competition_ = getDefaultInstance().getCompetition();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Competition (e.g., "Bundesliga" or "UEFA Champtionsleague")
       * </pre>
       *
       * <code>string competition = 9;</code>
       */
      public Builder setCompetitionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        competition_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object venue_ = "";
      /**
       * <pre>
       * Venue (e.g., "St. Jakob-Park" or "Maracana")
       * </pre>
       *
       * <code>string venue = 10;</code>
       */
      public java.lang.String getVenue() {
        java.lang.Object ref = venue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          venue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Venue (e.g., "St. Jakob-Park" or "Maracana")
       * </pre>
       *
       * <code>string venue = 10;</code>
       */
      public com.google.protobuf.ByteString
          getVenueBytes() {
        java.lang.Object ref = venue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          venue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Venue (e.g., "St. Jakob-Park" or "Maracana")
       * </pre>
       *
       * <code>string venue = 10;</code>
       */
      public Builder setVenue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        venue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Venue (e.g., "St. Jakob-Park" or "Maracana")
       * </pre>
       *
       * <code>string venue = 10;</code>
       */
      public Builder clearVenue() {
        
        venue_ = getDefaultInstance().getVenue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Venue (e.g., "St. Jakob-Park" or "Maracana")
       * </pre>
       *
       * <code>string venue = 10;</code>
       */
      public Builder setVenueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        venue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object objectRenameMap_ = "";
      /**
       * <pre>
       * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
       * </pre>
       *
       * <code>string objectRenameMap = 11;</code>
       */
      public java.lang.String getObjectRenameMap() {
        java.lang.Object ref = objectRenameMap_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          objectRenameMap_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
       * </pre>
       *
       * <code>string objectRenameMap = 11;</code>
       */
      public com.google.protobuf.ByteString
          getObjectRenameMapBytes() {
        java.lang.Object ref = objectRenameMap_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectRenameMap_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
       * </pre>
       *
       * <code>string objectRenameMap = 11;</code>
       */
      public Builder setObjectRenameMap(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        objectRenameMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
       * </pre>
       *
       * <code>string objectRenameMap = 11;</code>
       */
      public Builder clearObjectRenameMap() {
        
        objectRenameMap_ = getDefaultInstance().getObjectRenameMap();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String specifying the object rename map (e.g., "{200:BALL:Ball}%{1:A1:PLAYERNAMEA1}%{2:A2:PLAYERNAMEA2}%{4:A3:PLAYERNAMEA3}%...")
       * </pre>
       *
       * <code>string objectRenameMap = 11;</code>
       */
      public Builder setObjectRenameMapBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        objectRenameMap_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object teamRenameMap_ = "";
      /**
       * <pre>
       * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
       * </pre>
       *
       * <code>string teamRenameMap = 12;</code>
       */
      public java.lang.String getTeamRenameMap() {
        java.lang.Object ref = teamRenameMap_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          teamRenameMap_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
       * </pre>
       *
       * <code>string teamRenameMap = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTeamRenameMapBytes() {
        java.lang.Object ref = teamRenameMap_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teamRenameMap_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
       * </pre>
       *
       * <code>string teamRenameMap = 12;</code>
       */
      public Builder setTeamRenameMap(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        teamRenameMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
       * </pre>
       *
       * <code>string teamRenameMap = 12;</code>
       */
      public Builder clearTeamRenameMap() {
        
        teamRenameMap_ = getDefaultInstance().getTeamRenameMap();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String specifying the team rename map (e.g., "{ball:BALL:Ball}%{home:A:TEAMNAMEA}%{away:B:TEAMNAMEB}")
       * </pre>
       *
       * <code>string teamRenameMap = 12;</code>
       */
      public Builder setTeamRenameMapBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        teamRenameMap_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object videoPath_ = "";
      /**
       * <pre>
       * Path to the video file
       * </pre>
       *
       * <code>string videoPath = 13;</code>
       */
      public java.lang.String getVideoPath() {
        java.lang.Object ref = videoPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          videoPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Path to the video file
       * </pre>
       *
       * <code>string videoPath = 13;</code>
       */
      public com.google.protobuf.ByteString
          getVideoPathBytes() {
        java.lang.Object ref = videoPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Path to the video file
       * </pre>
       *
       * <code>string videoPath = 13;</code>
       */
      public Builder setVideoPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        videoPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Path to the video file
       * </pre>
       *
       * <code>string videoPath = 13;</code>
       */
      public Builder clearVideoPath() {
        
        videoPath_ = getDefaultInstance().getVideoPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Path to the video file
       * </pre>
       *
       * <code>string videoPath = 13;</code>
       */
      public Builder setVideoPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        videoPath_ = value;
        onChanged();
        return this;
      }

      private long matchStartVideoOffset_ ;
      /**
       * <pre>
       * Video offset (in s) of the start of the match
       * </pre>
       *
       * <code>int64 matchStartVideoOffset = 14;</code>
       */
      public long getMatchStartVideoOffset() {
        return matchStartVideoOffset_;
      }
      /**
       * <pre>
       * Video offset (in s) of the start of the match
       * </pre>
       *
       * <code>int64 matchStartVideoOffset = 14;</code>
       */
      public Builder setMatchStartVideoOffset(long value) {
        
        matchStartVideoOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Video offset (in s) of the start of the match
       * </pre>
       *
       * <code>int64 matchStartVideoOffset = 14;</code>
       */
      public Builder clearMatchStartVideoOffset() {
        
        matchStartVideoOffset_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object teamColorMap_ = "";
      /**
       * <pre>
       * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
       * </pre>
       *
       * <code>string teamColorMap = 15;</code>
       */
      public java.lang.String getTeamColorMap() {
        java.lang.Object ref = teamColorMap_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          teamColorMap_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
       * </pre>
       *
       * <code>string teamColorMap = 15;</code>
       */
      public com.google.protobuf.ByteString
          getTeamColorMapBytes() {
        java.lang.Object ref = teamColorMap_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teamColorMap_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
       * </pre>
       *
       * <code>string teamColorMap = 15;</code>
       */
      public Builder setTeamColorMap(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        teamColorMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
       * </pre>
       *
       * <code>string teamColorMap = 15;</code>
       */
      public Builder clearTeamColorMap() {
        
        teamColorMap_ = getDefaultInstance().getTeamColorMap();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String specifying the team color map (e.g., "{A:yellow}%{B:black}")
       * </pre>
       *
       * <code>string teamColorMap = 15;</code>
       */
      public Builder setTeamColorMapBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        teamColorMap_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:streamTeam.football.MatchMetadataStreamElementPayload)
    }

    // @@protoc_insertion_point(class_scope:streamTeam.football.MatchMetadataStreamElementPayload)
    private static final ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload();
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MatchMetadataStreamElementPayload>
        PARSER = new com.google.protobuf.AbstractParser<MatchMetadataStreamElementPayload>() {
      @java.lang.Override
      public MatchMetadataStreamElementPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchMetadataStreamElementPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MatchMetadataStreamElementPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MatchMetadataStreamElementPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.MatchMetadataStreamElementPayloadProtos.MatchMetadataStreamElementPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamTeam_football_MatchMetadataStreamElementPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamTeam_football_MatchMetadataStreamElementPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nMsrc/main/protobuf/streamTeam/football/" +
      "matchMetadataStreamElementPayload.proto\022" +
      "\023streamTeam.football\"\207\003\n!MatchMetadataSt" +
      "reamElementPayload\022;\n3generationTimestam" +
      "pFirstDataStreamElementOfTheMatch\030\001 \001(\003\022" +
      "\r\n\005sport\030\002 \001(\t\022\023\n\013fieldLength\030\003 \001(\001\022\022\n\nf" +
      "ieldWidth\030\004 \001(\001\022\021\n\tmirroredX\030\005 \001(\010\022\021\n\tmi" +
      "rroredY\030\006 \001(\010\022\021\n\tareaInfos\030\007 \001(\t\022\030\n\020matc" +
      "hStartUnixTs\030\010 \001(\003\022\023\n\013competition\030\t \001(\t\022" +
      "\r\n\005venue\030\n \001(\t\022\027\n\017objectRenameMap\030\013 \001(\t\022" +
      "\025\n\rteamRenameMap\030\014 \001(\t\022\021\n\tvideoPath\030\r \001(" +
      "\t\022\035\n\025matchStartVideoOffset\030\016 \001(\003\022\024\n\014team" +
      "ColorMap\030\017 \001(\tBm\nBch.unibas.dmi.dbis.str" +
      "eamTeam.dataStreamElements.protobuf.foot" +
      "ballB\'MatchMetadataStreamElementPayloadP" +
      "rotosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streamTeam_football_MatchMetadataStreamElementPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamTeam_football_MatchMetadataStreamElementPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamTeam_football_MatchMetadataStreamElementPayload_descriptor,
        new java.lang.String[] { "GenerationTimestampFirstDataStreamElementOfTheMatch", "Sport", "FieldLength", "FieldWidth", "MirroredX", "MirroredY", "AreaInfos", "MatchStartUnixTs", "Competition", "Venue", "ObjectRenameMap", "TeamRenameMap", "VideoPath", "MatchStartVideoOffset", "TeamColorMap", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
