// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/streamTeam/football/shotStatisticsStreamElementPayload.proto

package ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football;

public final class ShotStatisticsStreamElementPayloadProtos {
  private ShotStatisticsStreamElementPayloadProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShotStatisticsStreamElementPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:streamTeam.football.ShotStatisticsStreamElementPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Number of goals
     * </pre>
     *
     * <code>int64 numGoals = 1;</code>
     */
    long getNumGoals();

    /**
     * <pre>
     * Number of shots on target
     * </pre>
     *
     * <code>int64 numShotsOnTarget = 2;</code>
     */
    long getNumShotsOnTarget();

    /**
     * <pre>
     * Number of shots off target
     * </pre>
     *
     * <code>int64 numShotsOffTarget = 3;</code>
     */
    long getNumShotsOffTarget();
  }
  /**
   * <pre>
   * Payload of a shotStatistics stream element
   * </pre>
   *
   * Protobuf type {@code streamTeam.football.ShotStatisticsStreamElementPayload}
   */
  public  static final class ShotStatisticsStreamElementPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:streamTeam.football.ShotStatisticsStreamElementPayload)
      ShotStatisticsStreamElementPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShotStatisticsStreamElementPayload.newBuilder() to construct.
    private ShotStatisticsStreamElementPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShotStatisticsStreamElementPayload() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShotStatisticsStreamElementPayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShotStatisticsStreamElementPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numGoals_ = input.readInt64();
              break;
            }
            case 16: {

              numShotsOnTarget_ = input.readInt64();
              break;
            }
            case 24: {

              numShotsOffTarget_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.Builder.class);
    }

    public static final int NUMGOALS_FIELD_NUMBER = 1;
    private long numGoals_;
    /**
     * <pre>
     * Number of goals
     * </pre>
     *
     * <code>int64 numGoals = 1;</code>
     */
    public long getNumGoals() {
      return numGoals_;
    }

    public static final int NUMSHOTSONTARGET_FIELD_NUMBER = 2;
    private long numShotsOnTarget_;
    /**
     * <pre>
     * Number of shots on target
     * </pre>
     *
     * <code>int64 numShotsOnTarget = 2;</code>
     */
    public long getNumShotsOnTarget() {
      return numShotsOnTarget_;
    }

    public static final int NUMSHOTSOFFTARGET_FIELD_NUMBER = 3;
    private long numShotsOffTarget_;
    /**
     * <pre>
     * Number of shots off target
     * </pre>
     *
     * <code>int64 numShotsOffTarget = 3;</code>
     */
    public long getNumShotsOffTarget() {
      return numShotsOffTarget_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numGoals_ != 0L) {
        output.writeInt64(1, numGoals_);
      }
      if (numShotsOnTarget_ != 0L) {
        output.writeInt64(2, numShotsOnTarget_);
      }
      if (numShotsOffTarget_ != 0L) {
        output.writeInt64(3, numShotsOffTarget_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numGoals_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, numGoals_);
      }
      if (numShotsOnTarget_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, numShotsOnTarget_);
      }
      if (numShotsOffTarget_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, numShotsOffTarget_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload)) {
        return super.equals(obj);
      }
      ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload other = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload) obj;

      if (getNumGoals()
          != other.getNumGoals()) return false;
      if (getNumShotsOnTarget()
          != other.getNumShotsOnTarget()) return false;
      if (getNumShotsOffTarget()
          != other.getNumShotsOffTarget()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMGOALS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumGoals());
      hash = (37 * hash) + NUMSHOTSONTARGET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumShotsOnTarget());
      hash = (37 * hash) + NUMSHOTSOFFTARGET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumShotsOffTarget());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Payload of a shotStatistics stream element
     * </pre>
     *
     * Protobuf type {@code streamTeam.football.ShotStatisticsStreamElementPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:streamTeam.football.ShotStatisticsStreamElementPayload)
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.Builder.class);
      }

      // Construct using ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numGoals_ = 0L;

        numShotsOnTarget_ = 0L;

        numShotsOffTarget_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_descriptor;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload getDefaultInstanceForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.getDefaultInstance();
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload build() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload buildPartial() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload result = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload(this);
        result.numGoals_ = numGoals_;
        result.numShotsOnTarget_ = numShotsOnTarget_;
        result.numShotsOffTarget_ = numShotsOffTarget_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload) {
          return mergeFrom((ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload other) {
        if (other == ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload.getDefaultInstance()) return this;
        if (other.getNumGoals() != 0L) {
          setNumGoals(other.getNumGoals());
        }
        if (other.getNumShotsOnTarget() != 0L) {
          setNumShotsOnTarget(other.getNumShotsOnTarget());
        }
        if (other.getNumShotsOffTarget() != 0L) {
          setNumShotsOffTarget(other.getNumShotsOffTarget());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long numGoals_ ;
      /**
       * <pre>
       * Number of goals
       * </pre>
       *
       * <code>int64 numGoals = 1;</code>
       */
      public long getNumGoals() {
        return numGoals_;
      }
      /**
       * <pre>
       * Number of goals
       * </pre>
       *
       * <code>int64 numGoals = 1;</code>
       */
      public Builder setNumGoals(long value) {
        
        numGoals_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of goals
       * </pre>
       *
       * <code>int64 numGoals = 1;</code>
       */
      public Builder clearNumGoals() {
        
        numGoals_ = 0L;
        onChanged();
        return this;
      }

      private long numShotsOnTarget_ ;
      /**
       * <pre>
       * Number of shots on target
       * </pre>
       *
       * <code>int64 numShotsOnTarget = 2;</code>
       */
      public long getNumShotsOnTarget() {
        return numShotsOnTarget_;
      }
      /**
       * <pre>
       * Number of shots on target
       * </pre>
       *
       * <code>int64 numShotsOnTarget = 2;</code>
       */
      public Builder setNumShotsOnTarget(long value) {
        
        numShotsOnTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of shots on target
       * </pre>
       *
       * <code>int64 numShotsOnTarget = 2;</code>
       */
      public Builder clearNumShotsOnTarget() {
        
        numShotsOnTarget_ = 0L;
        onChanged();
        return this;
      }

      private long numShotsOffTarget_ ;
      /**
       * <pre>
       * Number of shots off target
       * </pre>
       *
       * <code>int64 numShotsOffTarget = 3;</code>
       */
      public long getNumShotsOffTarget() {
        return numShotsOffTarget_;
      }
      /**
       * <pre>
       * Number of shots off target
       * </pre>
       *
       * <code>int64 numShotsOffTarget = 3;</code>
       */
      public Builder setNumShotsOffTarget(long value) {
        
        numShotsOffTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of shots off target
       * </pre>
       *
       * <code>int64 numShotsOffTarget = 3;</code>
       */
      public Builder clearNumShotsOffTarget() {
        
        numShotsOffTarget_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:streamTeam.football.ShotStatisticsStreamElementPayload)
    }

    // @@protoc_insertion_point(class_scope:streamTeam.football.ShotStatisticsStreamElementPayload)
    private static final ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload();
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShotStatisticsStreamElementPayload>
        PARSER = new com.google.protobuf.AbstractParser<ShotStatisticsStreamElementPayload>() {
      @java.lang.Override
      public ShotStatisticsStreamElementPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShotStatisticsStreamElementPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShotStatisticsStreamElementPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShotStatisticsStreamElementPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.ShotStatisticsStreamElementPayloadProtos.ShotStatisticsStreamElementPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nNsrc/main/protobuf/streamTeam/football/" +
      "shotStatisticsStreamElementPayload.proto" +
      "\022\023streamTeam.football\"k\n\"ShotStatisticsS" +
      "treamElementPayload\022\020\n\010numGoals\030\001 \001(\003\022\030\n" +
      "\020numShotsOnTarget\030\002 \001(\003\022\031\n\021numShotsOffTa" +
      "rget\030\003 \001(\003Bn\nBch.unibas.dmi.dbis.streamT" +
      "eam.dataStreamElements.protobuf.football" +
      "B(ShotStatisticsStreamElementPayloadProt" +
      "osb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamTeam_football_ShotStatisticsStreamElementPayload_descriptor,
        new java.lang.String[] { "NumGoals", "NumShotsOnTarget", "NumShotsOffTarget", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
