// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/streamTeam/football/successfulPassEventStreamElementPayload.proto

package ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football;

public final class SuccessfulPassEventStreamElementPayloadProtos {
  private SuccessfulPassEventStreamElementPayloadProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SuccessfulPassEventStreamElementPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:streamTeam.football.SuccessfulPassEventStreamElementPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Length of the pass
     * </pre>
     *
     * <code>double length = 1;</code>
     */
    double getLength();

    /**
     * <pre>
     * Velocity of the pass
     * </pre>
     *
     * <code>double velocity = 2;</code>
     */
    double getVelocity();

    /**
     * <pre>
     * Angle of the pass in degree (in playing direction)
     * </pre>
     *
     * <code>double angle = 3;</code>
     */
    double getAngle();

    /**
     * <pre>
     * Direction category of the pass (in playing direction)
     * </pre>
     *
     * <code>string direction = 4;</code>
     */
    java.lang.String getDirection();
    /**
     * <pre>
     * Direction category of the pass (in playing direction)
     * </pre>
     *
     * <code>string direction = 4;</code>
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <pre>
     * Packing value of the pass
     * </pre>
     *
     * <code>int32 packing = 5;</code>
     */
    int getPacking();
  }
  /**
   * <pre>
   * Payload of a successfulPassEvent stream element
   * </pre>
   *
   * Protobuf type {@code streamTeam.football.SuccessfulPassEventStreamElementPayload}
   */
  public  static final class SuccessfulPassEventStreamElementPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:streamTeam.football.SuccessfulPassEventStreamElementPayload)
      SuccessfulPassEventStreamElementPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SuccessfulPassEventStreamElementPayload.newBuilder() to construct.
    private SuccessfulPassEventStreamElementPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SuccessfulPassEventStreamElementPayload() {
      direction_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SuccessfulPassEventStreamElementPayload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SuccessfulPassEventStreamElementPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              length_ = input.readDouble();
              break;
            }
            case 17: {

              velocity_ = input.readDouble();
              break;
            }
            case 25: {

              angle_ = input.readDouble();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              direction_ = s;
              break;
            }
            case 40: {

              packing_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.Builder.class);
    }

    public static final int LENGTH_FIELD_NUMBER = 1;
    private double length_;
    /**
     * <pre>
     * Length of the pass
     * </pre>
     *
     * <code>double length = 1;</code>
     */
    public double getLength() {
      return length_;
    }

    public static final int VELOCITY_FIELD_NUMBER = 2;
    private double velocity_;
    /**
     * <pre>
     * Velocity of the pass
     * </pre>
     *
     * <code>double velocity = 2;</code>
     */
    public double getVelocity() {
      return velocity_;
    }

    public static final int ANGLE_FIELD_NUMBER = 3;
    private double angle_;
    /**
     * <pre>
     * Angle of the pass in degree (in playing direction)
     * </pre>
     *
     * <code>double angle = 3;</code>
     */
    public double getAngle() {
      return angle_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object direction_;
    /**
     * <pre>
     * Direction category of the pass (in playing direction)
     * </pre>
     *
     * <code>string direction = 4;</code>
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Direction category of the pass (in playing direction)
     * </pre>
     *
     * <code>string direction = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKING_FIELD_NUMBER = 5;
    private int packing_;
    /**
     * <pre>
     * Packing value of the pass
     * </pre>
     *
     * <code>int32 packing = 5;</code>
     */
    public int getPacking() {
      return packing_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0D) {
        output.writeDouble(1, length_);
      }
      if (velocity_ != 0D) {
        output.writeDouble(2, velocity_);
      }
      if (angle_ != 0D) {
        output.writeDouble(3, angle_);
      }
      if (!getDirectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, direction_);
      }
      if (packing_ != 0) {
        output.writeInt32(5, packing_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, length_);
      }
      if (velocity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, velocity_);
      }
      if (angle_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, angle_);
      }
      if (!getDirectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, direction_);
      }
      if (packing_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, packing_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload)) {
        return super.equals(obj);
      }
      ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload other = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload) obj;

      if (java.lang.Double.doubleToLongBits(getLength())
          != java.lang.Double.doubleToLongBits(
              other.getLength())) return false;
      if (java.lang.Double.doubleToLongBits(getVelocity())
          != java.lang.Double.doubleToLongBits(
              other.getVelocity())) return false;
      if (java.lang.Double.doubleToLongBits(getAngle())
          != java.lang.Double.doubleToLongBits(
              other.getAngle())) return false;
      if (!getDirection()
          .equals(other.getDirection())) return false;
      if (getPacking()
          != other.getPacking()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLength()));
      hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVelocity()));
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAngle()));
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + PACKING_FIELD_NUMBER;
      hash = (53 * hash) + getPacking();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Payload of a successfulPassEvent stream element
     * </pre>
     *
     * Protobuf type {@code streamTeam.football.SuccessfulPassEventStreamElementPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:streamTeam.football.SuccessfulPassEventStreamElementPayload)
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.class, ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.Builder.class);
      }

      // Construct using ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        length_ = 0D;

        velocity_ = 0D;

        angle_ = 0D;

        direction_ = "";

        packing_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_descriptor;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload getDefaultInstanceForType() {
        return ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.getDefaultInstance();
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload build() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload buildPartial() {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload result = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload(this);
        result.length_ = length_;
        result.velocity_ = velocity_;
        result.angle_ = angle_;
        result.direction_ = direction_;
        result.packing_ = packing_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload) {
          return mergeFrom((ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload other) {
        if (other == ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload.getDefaultInstance()) return this;
        if (other.getLength() != 0D) {
          setLength(other.getLength());
        }
        if (other.getVelocity() != 0D) {
          setVelocity(other.getVelocity());
        }
        if (other.getAngle() != 0D) {
          setAngle(other.getAngle());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          onChanged();
        }
        if (other.getPacking() != 0) {
          setPacking(other.getPacking());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double length_ ;
      /**
       * <pre>
       * Length of the pass
       * </pre>
       *
       * <code>double length = 1;</code>
       */
      public double getLength() {
        return length_;
      }
      /**
       * <pre>
       * Length of the pass
       * </pre>
       *
       * <code>double length = 1;</code>
       */
      public Builder setLength(double value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Length of the pass
       * </pre>
       *
       * <code>double length = 1;</code>
       */
      public Builder clearLength() {
        
        length_ = 0D;
        onChanged();
        return this;
      }

      private double velocity_ ;
      /**
       * <pre>
       * Velocity of the pass
       * </pre>
       *
       * <code>double velocity = 2;</code>
       */
      public double getVelocity() {
        return velocity_;
      }
      /**
       * <pre>
       * Velocity of the pass
       * </pre>
       *
       * <code>double velocity = 2;</code>
       */
      public Builder setVelocity(double value) {
        
        velocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Velocity of the pass
       * </pre>
       *
       * <code>double velocity = 2;</code>
       */
      public Builder clearVelocity() {
        
        velocity_ = 0D;
        onChanged();
        return this;
      }

      private double angle_ ;
      /**
       * <pre>
       * Angle of the pass in degree (in playing direction)
       * </pre>
       *
       * <code>double angle = 3;</code>
       */
      public double getAngle() {
        return angle_;
      }
      /**
       * <pre>
       * Angle of the pass in degree (in playing direction)
       * </pre>
       *
       * <code>double angle = 3;</code>
       */
      public Builder setAngle(double value) {
        
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Angle of the pass in degree (in playing direction)
       * </pre>
       *
       * <code>double angle = 3;</code>
       */
      public Builder clearAngle() {
        
        angle_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <pre>
       * Direction category of the pass (in playing direction)
       * </pre>
       *
       * <code>string direction = 4;</code>
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Direction category of the pass (in playing direction)
       * </pre>
       *
       * <code>string direction = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Direction category of the pass (in playing direction)
       * </pre>
       *
       * <code>string direction = 4;</code>
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Direction category of the pass (in playing direction)
       * </pre>
       *
       * <code>string direction = 4;</code>
       */
      public Builder clearDirection() {
        
        direction_ = getDefaultInstance().getDirection();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Direction category of the pass (in playing direction)
       * </pre>
       *
       * <code>string direction = 4;</code>
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        direction_ = value;
        onChanged();
        return this;
      }

      private int packing_ ;
      /**
       * <pre>
       * Packing value of the pass
       * </pre>
       *
       * <code>int32 packing = 5;</code>
       */
      public int getPacking() {
        return packing_;
      }
      /**
       * <pre>
       * Packing value of the pass
       * </pre>
       *
       * <code>int32 packing = 5;</code>
       */
      public Builder setPacking(int value) {
        
        packing_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Packing value of the pass
       * </pre>
       *
       * <code>int32 packing = 5;</code>
       */
      public Builder clearPacking() {
        
        packing_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:streamTeam.football.SuccessfulPassEventStreamElementPayload)
    }

    // @@protoc_insertion_point(class_scope:streamTeam.football.SuccessfulPassEventStreamElementPayload)
    private static final ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload();
    }

    public static ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SuccessfulPassEventStreamElementPayload>
        PARSER = new com.google.protobuf.AbstractParser<SuccessfulPassEventStreamElementPayload>() {
      @java.lang.Override
      public SuccessfulPassEventStreamElementPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuccessfulPassEventStreamElementPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SuccessfulPassEventStreamElementPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SuccessfulPassEventStreamElementPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ch.unibas.dmi.dbis.streamTeam.dataStreamElements.protobuf.football.SuccessfulPassEventStreamElementPayloadProtos.SuccessfulPassEventStreamElementPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nSsrc/main/protobuf/streamTeam/football/" +
      "successfulPassEventStreamElementPayload." +
      "proto\022\023streamTeam.football\"~\n\'Successful" +
      "PassEventStreamElementPayload\022\016\n\006length\030" +
      "\001 \001(\001\022\020\n\010velocity\030\002 \001(\001\022\r\n\005angle\030\003 \001(\001\022\021" +
      "\n\tdirection\030\004 \001(\t\022\017\n\007packing\030\005 \001(\005Bs\nBch" +
      ".unibas.dmi.dbis.streamTeam.dataStreamEl" +
      "ements.protobuf.footballB-SuccessfulPass" +
      "EventStreamElementPayloadProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streamTeam_football_SuccessfulPassEventStreamElementPayload_descriptor,
        new java.lang.String[] { "Length", "Velocity", "Angle", "Direction", "Packing", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
